# SConstruct
# 
# Build file for Aqua
#
# This file is part of Aqua Universal Gesture Recognition Framework.
# Copyright (C) 2010  Jay Roltgen.
#
# Aqua is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

env = Environment()
myLibs = []

#Add the /Ehsc flag to the msvc compiler
if (env['CC'] == 'cl'):
    env.Append(CCFLAGS = ['/EHsc'])
    #env['PDB'] = 'Aqua.pdb'
    #env[
    myLibs.append('WS2_32')
    
env.Program('bin/Aqua', 
            Glob('*.cpp') + Glob('utils/*.cpp') + \
            ['events/EventFactory.cpp', \
             'gestures/GestureFactory.cpp'], \
            LIBS=myLibs)

#Events
env.SharedLibrary('bin/events/UnifiedEvent', 'events/UnifiedEvent.cpp')
env.SharedLibrary('bin/events/UnifiedDragEvent', 'events/UnifiedDragEvent.cpp')

#Gestures
env.SharedLibrary('bin/gestures/HelloWorldGesture', 'gestures/HelloWorldGesture.cpp')
env.SharedLibrary('bin/gestures/YouRockGesture', 'gestures/YouRockGesture.cpp')
env.SharedLibrary('bin/gestures/PrintEventGesture', 'gestures/PrintEventGesture.cpp')

#Unified Gestures
#env.SharedLibrary('bin/gestures/UnifiedStandardDynamicGesture', ['gestures/unifiedGestures/UnifiedStandardDynamicGesture.cpp'])
