# SConstruct
#  - Build file for Jay Roltgen's thesis project
#
# Author: Jay Roltgen (jroltgen@gmail.com)

env = Environment()
myLibs = []

#Add the /Ehsc flag to the msvc compiler
if (env['CC'] == 'cl'):
    env.Append(CCFLAGS = ['/EHsc'])
    myLibs.append('WS2_32')
    
env.Program('Aqua', 
            Glob('*.cpp') + Glob('utils/*.cpp') + \
            ['events/EventFactory.cpp', \
             'events/Event.cpp', \
             'gestures/GestureFactory.cpp'], \
            LIBS=myLibs)

#Events
env.SharedLibrary('events/SimpleEvent', ['events/SimpleEvent.cpp', 'events/Event.cpp'])
env.SharedLibrary('events/Event', 'events/Event.cpp')

#Gestures
env.SharedLibrary('gestures/HelloWorldGesture', ['gestures/HelloWorldGesture.cpp', 'events/Event.cpp'])
env.SharedLibrary('gestures/YouRockGesture', ['gestures/YouRockGesture.cpp', 'events/Event.cpp'])
env.SharedLibrary('gestures/PrintEventGesture', ['gestures/PrintEventGesture.cpp', 'events/Event.cpp'])