# This is a simple scons build file.
# 
# This file is part of Aqua Universal Gesture Recognition Framework.
# Copyright (C) 2010 Iowa State University.
#
# Aqua is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


 

# Specify the source files in list format here.
# e.g.: source_files = ['source1.cpp', source2.cpp', 'etc..']
env = Environment()
env.Append(CCFLAGS = ['/EHsc', '/W2'])

source_files = ['FlickEvent.cpp']

# Specify the library file name here
# e.g.: SharedLibrary('MyEventName', source_files)
env.SharedLibrary('FlickEvent', source_files)