env = Environment()
if (env['CC'] == 'cl'):
    env.Append(CCFLAGS = ['/EHsc', '/W2'])
else:
    myLibs.append('pthread')
    
source_files = ['UnifiedKineticGesture.cpp', 'events/UnifiedEvent.cpp']
env.SharedLibrary('UnifiedKineticGesture', source_files)